# Generated by Django 5.1.6 on 2025-02-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscription',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
