# Generated by Django 5.1.6 on 2025-03-03 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_subscription_alter_client_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('minutes', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnlimitedSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_finish', models.DateField()),
                ('period', models.CharField(choices=[('М', 'Месяц'), ('ПГ', 'Полгода'), ('Г', 'Год')])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='minutes',
        ),
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('UL', 'Безлимитный'), ('M', 'Минутный')], null=True),
        ),
    ]
