# Generated by Django 5.1.6 on 2025-03-03 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_minutesubscription_unlimitedsubscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='minute_subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.minutesubscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='unlimited_subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.unlimitedsubscription'),
        ),
    ]
