# Generated by Django 5.1.6 on 2025-03-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_subscription_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutesubscription',
            name='number',
        ),
        migrations.RemoveField(
            model_name='unlimitedsubscription',
            name='number',
        ),
    ]
