# Generated by Django 5.1.6 on 2025-03-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_minutesubscription_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='minute_subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.minutesubscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unlimited_subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.unlimitedsubscription'),
        ),
    ]
