# Generated by Django 5.1.6 on 2025-03-06 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_subscription_minute_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutesubscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='minute_subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='unlimited_subscription',
        ),
        migrations.RemoveField(
            model_name='unlimitedsubscription',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='unlimitedsubscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='minutesubscription',
            name='subscription_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='type_sub',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='unlimitedsubscription',
            name='subscription_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.subscription'),
        ),
    ]
