# Generated by Django 5.1.6 on 2025-03-20 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_minutesubscription_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutesubscription',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='unlimitedsubscription',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='minute_subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.minutesubscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='unlimited_subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.unlimitedsubscription'),
        ),
    ]
