# Generated by Django 5.1.6 on 2025-03-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_minutesubscription_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=18),
        ),
    ]
