# Generated by Django 5.1.6 on 2025-03-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_subscription_minute_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlimitedsubscription',
            name='date_finish',
        ),
    ]
