# Generated by Django 5.1.6 on 2025-03-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_unlimitedsubscription_date_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlimitedsubscription',
            name='end_at',
            field=models.DateField(null=True),
        ),
    ]
