# Generated by Django 5.1.6 on 2025-04-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_unlimitedsubscription_end_at'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='minute_subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='unlimited_subscription',
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription'),
        ),
        migrations.DeleteModel(
            name='MinuteSubscription',
        ),
        migrations.DeleteModel(
            name='UnlimitedSubscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
