# Generated by Django 5.1.6 on 2025-04-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_alter_clientrecords_cream_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientRecords',
        ),
    ]
