# Generated by Django 5.1.6 on 2025-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0018_delete_clientrecords'),
        ('creams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_subscription', models.BooleanField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('tanning_booth', models.CharField(choices=[('В', 'Вертикальный'), ('Г', 'Горизонтальный')], max_length=2)),
                ('minutes', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('cream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creams.creams')),
            ],
        ),
    ]
