# Generated by Django 5.1.6 on 2025-04-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_remove_client_subscription'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
